#!/bin/bash
export SUDO_ASKPASS=/usr/bin/ssh-askpass 
export _JAVA_AWT_WM_NONREPARENTING=1


picom --vsync --backend glx -b
pulseaudio -D
/usr/lib/notification-daemon/notification-daemon &


feh --bg-fill ~/Nextcloud/Images/Furry/Commis/Kat-LUK.J_/poster_etha.png


# Fix touchscreen
xinput set-prop "pointer:ELAN22A6:00 04F3:22A6" --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1
# setup touchpad parameters
touchpadid=`xinput list | grep Touchpad | cut -d= -f2 | cut -f1`
tapid=`xinput list-props $touchpadid | grep "Tapping Enabled" | grep -v "Default" | cut -d'(' -f2 | cut -d')' -f1`
middleid=`xinput list-props $touchpadid | grep "Middle Emulation Enabled" | grep -v "Default" | cut -d'(' -f2 | cut -d')' -f1`
scrollid=`xinput list-props $touchpadid | grep "Natural Scrolling Enabled" | grep -v "Default" | cut -d'(' -f2 | cut -d')' -f1`
speedid=`xinput list-props $touchpadid | grep "Coordinate Transformation Matrix" | grep -v "Default" | cut -d'(' -f2 | cut -d')' -f1`
disablewhiletypingid=`xinput list-props $touchpadid | grep "Disable While Typing Enabled" | grep -v "Default" | cut -d'(' -f2 | cut -d')' -f1`
xinput set-prop $touchpadid $tapid 1
xinput set-prop $touchpadid $middleid 1
xinput set-prop $touchpadid $scrollid 0
xinput set-prop $touchpadid $speedid 5 0 0 0 5 0 0 0 2
xinput set-prop $touchpadid $disablewhiletypingid 0


nextcloud --background &
kdeconnect-indicator &


source /opt/qtile/venv/bin/activate
python /opt/qtile/bin/qtile $* > /opt/qtile/qtile.log

